## Time to wait to remove an uplink after being forwarded.
##
## Making this too short could lead to duplicate posts for the 
## same packets from gateways that are slow.
cleanup_window = "30s"

# Listen address for metrics requests.
metrics_listen = "0.0.0.0:9002"

## GRPC Uplink messages from Helium Packet Router.
uplink_listen = "0.0.0.0:9000"

## Endpoint of LNS for all roaming messages.
lns_endpoint = "http://localhost:9005"

## HTTP Roaming specific settings
[roaming]
## Roaming Protocol Version
protocol_version = "1.1"

## Main Helium NetID.
sender_net_id = "C00053"

## NetID of the target network.
receiver_net_id = "000000"

## The unique identity of this fNS
sender_nsid = "6081FFFE12345678"

## The unique identify of the target receiver
receiver_nsid = "0000000000000000"

## Time to wait for uplink deduplication.
dedup_window = "250ms"

## Not all LNSs handle a PRStartNotif message after a JoinAccept has been sent.
send_pr_start_notif = false

## HTTP Downlink messages from LNS.
downlink_listen = "0.0.0.0:9001"

## GWMP Specific settings
[region_port_mapping]
## Us915 = 1700
## Au915 = 1701